### ISSUE TITLE
TypeError: item.properties is undefined

### ISSUE THREAD

**Issue by azcn2503** [aykutkardas/react-icomoon#29]
Hello,

It looks like the iconset JSON exported from the IcoMoon App (https://icomoon.io/app/#/select) is not providing a `properties` prop within its icon definitions any more. 

Example of an icon definition taken from the JSON:

```json
    {
      "paths": [
        "M320 192c0-106.039 85.961-192 192-192s192 85.961 192 192c0 106.039-85.961 192-192 192s-192-85.961-192-192zM768.078 448h-35.424l-199.104 404.244 74.45-372.244-96-96-96 96 74.45 372.244-199.102-404.244h-35.424c-127.924 0-127.924 85.986-127.924 192v320h768v-320c0-106.014 0-192-127.922-192z"
      ],
      "tags": [
        "user-tie",
        "user",
        "user-employee",
        "profile",
        "avatar",
        "person",
        "member",
        "job",
        "official"
      ],
      "defaultCode": 59766,
      "grid": 16
    },
```

So trying to render an icon using a `icon` prop throws an error due to the check here: https://github.com/aykutkardas/react-icomoon/blob/master/src/index.tsx#L60 since `properties` is undefined.

**Comment by aykutkardas** [comment]
Icomoon gives this file when you download it as a font.

Step 1: Select icons

Step 2: Click Generate Font
![image](https://user-images.githubusercontent.com/7966133/154856074-cb9abd93-50f8-4f01-859d-4dd1c386d8c8.png)

Step 3: Download Font
![image](https://user-images.githubusercontent.com/7966133/154856089-cbac4517-f45b-4ce8-8787-a20cc2eba1a7.png)

The zip you downloaded will contain a `selection.json` file.


---

 

I will soon announce a project that facilitates this process. 
By using this project instead of Icomoon, you will be able to generate the `selection.json` file in seconds. 🎉

**Comment by azcn2503** [comment]
Much appreciated! I was using the menu at the top right of the app to download the selection JSON.
